### ISSUE TITLE
Porg fails to log install of Musl, skalibs, execline, s6-* packages

### ISSUE THREAD

**Issue by dslm4515** [dslm4515/Musl-LFS#10]
Porg can be patched to build under musl, but certain commands during `make install` will not log:

```
exec ./tools/install.sh -D -m 644 src/includ/include/s6/ftrigr.h
exec ./tools/install.sh -D -m 644 src/includ /usr/include/s6/accessrules.h
exec ./tools/install.sh -D -m 644 src/includ/include/s6/config.h
porg: s6-2.7.2.2: No files to log
```

In case it matters, issue happens with both `/tools/bin/porg` and `/bin/porg`

_Porg is no longer maintained, would be nice to find a good replacement that can log install (files installed) and remove packages based on that log_

**Comment by dslm4515** [comment]
@firasuke and @mssx86, any suggestions on a fix or an alternative? 

_Porg originally fails to build because of these functions_

- `__open()`
- `_open64()`
- `fopen()`
- `freopen()`
- `open64()`
- `creat64()`
- `openat64()`

Otherwise I might switch to pkgtool that Slackware uses.

**Comment by firasuke** [comment]
Honestly, I'd recommend against using `porg` as it fails to build under `musl` without patching, and is no longer maintained.

For *LFS projects, I suggest that you pick the _"Creating Package Archives"_ method listed in the [Package Management](http://www.linuxfromscratch.org/lfs/view/8.1/chapter06/pkgmgt.html) of LFS.

> Otherwise I might switch to pkgtool that Slackware uses.
I can't agree more, as [Slackware's package management system/scheme](http://www.slackbook.org/html/package-management.html) works best with *LFS projects.

**Comment by dslm4515** [comment]
I'll close issue. Porg is good for tracking files during most package installs but I'll not use it as a package manager.
