### ISSUE TITLE
applying the i18n patch for coreutils causes the make to fail, builds fine without it.

### ISSUE THREAD

**Issue by mssx86** [dslm4515/Musl-LFS#11]
applying the `coreutils-8.31-i18n-1.patch` patch causes the build to die with this error:
```
/usr/bin/ld: src/expand.o: in function `expand':
expand.c:(.text+0x4cd): undefined reference to `mbfile_multi_getc'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:8824: src/expand] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/sources/coreutils-8.31'
make[1]: *** [Makefile:12651: all-recursive] Error 1
make[1]: Leaving directory '/sources/coreutils-8.31'
make: *** [Makefile:6831: all] Error 2
```
it builds fine when the patch is not applied. it makes more sense to add a disclaimer to say that the step is optional like the original *linux from scratch* book does since it's not necessary or to remove it.

**Comment by mssx86** [comment]
just finished the build and i'm able to boot to it, although i used sysvinit and my own set of init scripts. thanks for putting these together again.

created a pull request to fix some of the minor things as usual, i'll be really happy if you can check them out.

**Comment by dslm4515** [comment]
Yup. Got the same error on a x86_64-glibc host. Gonna just remove it as musl doesn’t have support for locales ... nor have I found a good alternative
