### ISSUE TITLE
Missing SHA for sources

### ISSUE THREAD

**Issue by MadHau5** [dslm4515/Musl-LFS#23]
The sources do not have a provided sha-sum file to check integrity.

**Comment by MadHau5** [comment]
For example, my `file-5.37.tar.gz` was corrupted and I didn't know until I attempted to compile it and it gave an error.

**Comment by mssx86** [comment]
most software listed here are out of date. best thing to do would be using this documentation as a base and getting up to date software from official mirrors and checking the integrity as you go.

patches or modifications to the vanilla sources required to build the new versions can be acquired from alpine, void and kiss. gentoo's libressl overlay provides patches for building with libressl.

you can check [this](https://github.com/mssx86/apathy#building-a-similar-system) out as well.

**Comment by MadHau5** [comment]
A question, if you will. My cross-compile gcc didn't build but my architecture is marked "pass", so which distro did it pass on (I'm on Arch btw)?

**Comment by mssx86** [comment]
i don't know which branch you're trying to build from but when i forked mlfs there were problems with the host leaking if the host libc is glibc. you might want to try installing alpine in a chroot and go from there.

**Comment by dslm4515** [comment]
> A question, if you will. My cross-compile gcc didn't build but my architecture is marked "pass", so which distro did it pass on (I'm on Arch btw)?

For all architectures listed with "pass", host system ran either LFS or a previous MLFS build.


The machines I build on are low on memory and CPU speed, so I choose to build on a LFS system to minimize resource usage by the host system.

**Comment by dslm4515** [comment]
> i don't know which branch you're trying to build from but when i forked mlfs there were problems with the host leaking if the host libc is glibc. you might want to try installing alpine in a chroot and go from there.

Since stable-6.00 branch, I fixed the host leaking. In fact, I am actually testing out stable-7.00 branch on archlinux(glibc). Cross tool chain is complete, currently working on the tool chain that builds the final system.
