### ISSUE TITLE
Eudev rules

### ISSUE THREAD

**Issue by ilobilo** [dslm4515/Musl-LFS#45]
Where is mlfs udev rules?

**Comment by dslm4515** [comment]
Sorry, looks like I forgot to add it to the repo. It can be found here:
https://github.com/dslm4515/MLFS-pkgtool/tree/1.00/files/udev-mlfs-20191014

**Comment by dslm4515** [comment]
Fixed in commit 799c48d for master and commit fb3a00e for stable-8.00
