### ISSUE TITLE
Files not present: files/utmps-alpine/*.pc

### ISSUE THREAD

**Issue by LostGhost1** [dslm4515/Musl-LFS#59]
When building the final system (section 03 - Chroot), compiling utmp, you are asked to do the following:

```
# Set the version in pkconfig file
cp -v ../files/utmps-alpine/*.pc /tmp/
sed -i -e "s/@@VERSION@@/0.1.0.2/g" -- /tmp/*.pc 
```
However, there is no such directory as files/utmps-alpine! Am I missing something?

**Comment by dslm4515** [comment]
Hmmm. Let me check if it's a typo or missing.

**Comment by dslm4515** [comment]
Looks like it was accidentally deleted in version 9.00. Version 8.00 of this repo has it.

**Comment by dslm4515** [comment]
Added missing file with commit cdfb765

Thanks!
