### ISSUE TITLE
doc/3-Chroot/004-Create_Essential_Files_and_Links: `bin:bin` is deprecated since before Linux was even created

### ISSUE THREAD

**Issue by takusuman** [dslm4515/Musl-LFS#66]
The bin user is considered insecure and deprecated since mid-80's and the most part of UNIX security books/manuals recommend `chown`ing it to `root:wheel` --- for instance, FreeBSD have been doing it since 1998 (https://github.com/freebsd/freebsd-src/commit/7faa559f34d8e1b2991d11274edcbe0bf3458336). 

Related unix.SE thread: https://unix.stackexchange.com/a/485506

**Comment by dslm4515** [comment]
That's good point.

In all my experience working and developing Linux/Unix systems, I never used or needed the bin user

**Comment by dslm4515** [comment]
Fixed in commit 7f8506a7873083ffaad82584ac7b1b2c4416e1b7
