### ISSUE TITLE
2-toolchain/33-vim: configure: error: cross-compiling: please set 'vim_cv_toupper_broken'

### ISSUE THREAD

**Issue by takusuman** [dslm4515/Musl-LFS#67]
Before continuing, is this bug normal?

**Comment by takusuman** [comment]
Apparently, its not finding ncurses... but I've compiled it correctly.

**Comment by takusuman** [comment]
Ok, that's strange.
![image](https://user-images.githubusercontent.com/47103338/150845095-ba124286-3116-4fd9-84ac-6b66bcb8394d.png)

**Comment by takusuman** [comment]
"Solved" it at first linking `libncursesw.so` to `libcurses.so` on /tools/lib, but I'm watching and expecting more errors (kind of pessimism of my part).

To be honest, my will is to say a lot of curse words, but I'll keep the class here in respect to you guys.

**Comment by takusuman** [comment]
FUCK YEAH, IT COMPILED!

**Comment by takusuman** [comment]
Sorry for the "f-word" anyway, I needed to say it.

**Comment by dslm4515** [comment]
Actually this has happened to me for a couple of builds… even more with using netbsd’s curses. Although I don’t think it shows up when in chroot.

**Comment by dslm4515** [comment]
> IT COMPILED

oh I know that feeling oh too well with building against musl, lol
