### ISSUE TITLE
071-IPRoute2: error: static declaration of 'setns' follows non-static declaration

### ISSUE THREAD

**Issue by takusuman** [dslm4515/Musl-LFS#73]
I was trying to compile IPRoute2 and just got this error.
There's nothing unusual on my CFLAGS (in fact, it's empty).
Any clue of what can be happening?

> sh configure /usr/include
> TC schedulers
>  ATM    no
> 
> libc has setns: no
> SELinux support: no
> libbpf support: no
> ELF support: yes
> libmnl support: no
> Berkeley DB: no
> need for strlcpy: yes
> libcap support: yes
> 
> lib
>     CC       libgenl.o
>     CC       libnetlink.o
> libnetlink.c:154:2: warning: #warning "libmnl required for error support" [-Wcpp]
>   154 | #warning "libmnl required for error support"
>       |  ^~~~~~~
>     AR       libnetlink.a
>     CC       utils.o
> In file included from utils.c:41:
> ../include/namespace.h:41:19: error: static declaration of 'setns' follows non-static declaration
>    41 | static inline int setns(int fd, int nstype)
>       |                   ^~~~~
> In file included from ../include/namespace.h:5,
>                  from utils.c:41:
> /usr/include/sched.h:78:5: note: previous declaration of 'setns' was here
>    78 | int setns(int, int);
>       |     ^~~~~
> make[1]: *** [utils.o] Error 1
> make: *** [all] Error 2
>

**Comment by dslm4515** [comment]
Strange. Are you using the latest version of iproute2? I can't remember what version my latest build uses... I'll have to check once I'm back at my desk.

**Comment by takusuman** [comment]
> Are you using the latest version of iproute2?

I'm using the same version that Musl-LFS 9.00, the 5.12.0 version.
Alpine Linux uses an older version (4.13.0) with some patches to work with musl, apparently.
https://git.alpinelinux.org/aports/tree/main/iproute2/APKBUILD?h=3.9-stable

**Comment by takusuman** [comment]
Ok, screw it.
If I can't get this working tomorrow morning, I'll assume that this is some error that I've done and redo the chroot stage again from scratch.

**Comment by dslm4515** [comment]
I'm building another MLFS build.
_Last build was messy, trying to get Vulkan support to work. I also realized, I should install non-essential packages in /opt instead of /usr, such as X11/Xorg and wlroots._

I am now at the same point, building IPRoute2. But building version 5.16.0. 
```
ax25_ntop.c:5:10: fatal error: netax25/ax25.h: No such file or directory
    5 | #include <netax25/ax25.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../config.mk:39: ax25_ntop.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:73: all] Error 2
```

I will check Alpine and Void

**Comment by dslm4515** [comment]
Alpine shows dependencies for `libax25` and `libmnl` ... yet LFS, shows neither package built.

Perhaps, kernel headers are old on my build?

**Comment by takusuman** [comment]
> Nope. Building iproute2-5.17.0 builds fine:
> 
> ```
> $ sed -i /ARPD/d Makefile
> $ rm -fv man/man8/arpd.8
> $ sed -i 's/.m_ipt.o//' tc/Makefile
> $ make NETNS_RUN_DIR=/run/netns
> $ make DOCDIR=/usr/share/doc/iproute2-5.17.0 install
> ```

I'll try to build 5.17.0 when I get there again.

**Comment by takusuman** [comment]
> libc has setns: no

Touché.
