### ISSUE TITLE
Why are our ``CFLAGS`` equal to ``-g0 -O0``?

### ISSUE THREAD

**Issue by takusuman** [dslm4515/Musl-LFS#75]
There's a more in-depth explanation of why are we using these?

Reference: https://github.com/dslm4515/Musl-LFS/blob/stable-9.00/doc/2-toolchain/04-gcc#L76-L77

**Comment by dslm4515** [comment]
If I remember correctly it was to speed up the compile time for GCC and reduce debugging symbols.

I would have to check through the commits

**Comment by dslm4515** [comment]
Per commit c8d6a00cca1105206ac622f3752c113871a1b39c

CFLAGS was set to `-g0 -O0` to disable optimizations to speed up compile time of GCC. _GCC built for the toolchain `/tools` is not the GCC used in the final MLFS system. Therefore, any optimizations would not be utilized in the final system._

**Comment by takusuman** [comment]
> CFLAGS was set to `-g0 -O0` to disable optimizations to speed up compile time of GCC

Gotcha!
