### ISSUE TITLE
What is posixtz (and why do we need it)?

### ISSUE THREAD

**Issue by takusuman** [dslm4515/Musl-LFS#80]
I couldn't find any information about it other than its source code. I've read the source code a little, but I didn't come to any precise conclusion.

I'm in a rush right now, sorry for not elaborating more.

Related: https://github.com/dslm4515/Musl-LFS/blob/master/doc/3-Chroot/011-Time_Zone_Utilities#L12

**Comment by takusuman** [comment]
Ok, I think I figured out: it is basically a utility to get the POSIX timezone code from tzdb.
Cool, I think I can close the case.

**Comment by dslm4515** [comment]
Cool! I always wanted to know. I think I got the idea to use it from Void or Alpine.

I forgot to keep track of dependencies, like in the LFS book, when I first got MLFS working. I used to include musl-rpmatch but later realized it's never used by any other package or even in B[M]LFS.
